package toxi.geom.util;

import java.io.FileOutputStream;
import java.io.PrintWriter;

import toxi.geom.Vec3D;

public class OBJWriter {

	final String VERSION = "0.24";

	FileOutputStream objStream;
	PrintWriter objWriter;

	void beginSave(String fn) {
		try {
			objStream = new FileOutputStream(fn);
			objWriter = new PrintWriter(objStream);
			objWriter.println("# generated by OBJExport v" + VERSION);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	void endSave() {
		try {
			objWriter.flush();
			objWriter.close();
			objStream.flush();
			objStream.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	void newObject(String name) {
		objWriter.println("o " + name);
	}

	void vertex(Vec3D v) {
		objWriter.println("v " + v.x + " " + v.y + " " + v.z);
	}

	void face(int a, int b, int c) {
		objWriter.println("f " + a + " " + b + " " + c);
	}

	void faceList() {
		objWriter.println("s off");
	}
}
