package toxi.geom.util;

import java.io.FileOutputStream;
import java.io.PrintWriter;

import toxi.geom.Vec3D;

/**
 * Extremely bare bones Wavefront OBJ 3D format exporter. Purely handles the
 * writing of data to the .obj file, but does not have any form of mesh
 * management.
 * 
 * Might get some more TLC in future versions.
 * 
 * @author toxi
 * 
 */
public class OBJWriter {

	public final String VERSION = "0.25";

	protected FileOutputStream objStream;
	protected PrintWriter objWriter;

	public void beginSave(String fn) {
		try {
			objStream = new FileOutputStream(fn);
			objWriter = new PrintWriter(objStream);
			objWriter.println("# generated by OBJExport v" + VERSION);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void endSave() {
		try {
			objWriter.flush();
			objWriter.close();
			objStream.flush();
			objStream.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void newObject(String name) {
		objWriter.println("o " + name);
	}

	public void vertex(Vec3D v) {
		objWriter.println("v " + v.x + " " + v.y + " " + v.z);
	}

	public void face(int a, int b, int c) {
		objWriter.println("f " + a + " " + b + " " + c);
	}

	public void faceList() {
		objWriter.println("s off");
	}
}
